import type { PortfolioItem } from "@/lib/types";
import { withBasePath } from "@/lib/base-path";
import { portfolioBlurMap } from "@/lib/content/portfolio-blur";

function buildImages(slug: string, count: number, title: string) {
  return Array.from({ length: count }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    const rawSrc = `/images/portfolio/${slug}/${n}.jpg`;
    return {
      src: withBasePath(rawSrc),
      alt: `${title} 현장 사진 ${i + 1}`,
      blurDataURL: portfolioBlurMap[rawSrc],
    };
  });
}

// "사진자료 내용정리.xlsx" 폴더명 기준으로 img_org/recent/ 실제 시공 사진과 매칭한 데이터입니다.
const rawPortfolioItems: PortfolioItem[] = [
  {
    slug: "un-forces-memorial-ceremony",
    title: "유엔군초전기념 추도식",
    category: "기념식",
    place: "야외",
    date: "2026.06.30",
    region: "오산시",
    organizer: "오산시",
    folder: "(260630)유엔군 초전기념 추도식",
    image: "/images/portfolio/un-forces-memorial-ceremony.jpg",
    imageAlt: "유엔군초전기념 추도식 야외 무대와 각국 국기 설치 전경",
    images: buildImages("un-forces-memorial-ceremony", 8, "유엔군초전기념 추도식"),
  },
  {
    slug: "memorial-theme-park",
    title: "메모리얼 테마파크",
    category: "팝업행사",
    place: "야외",
    date: "2026.06.26",
    region: "수원시",
    organizer: "경기남부보훈지청",
    folder: "(260626)메모리얼 테마파크",
    image: "/images/portfolio/memorial-theme-park.jpg",
    imageAlt: "메모리얼 테마파크 야외 게이트 조형물과 부스 설치 전경",
    images: buildImages("memorial-theme-park", 15, "메모리얼 테마파크"),
  },
  {
    slug: "heritage-concert",
    title: "헤리티지 콘서트",
    category: "콘서트",
    place: "야외",
    date: "2026.06.13",
    region: "수원시",
    organizer: "수원시 / OBS",
    folder: "(260613)헤리티지 콘서트",
    image: "/images/portfolio/heritage-concert.jpg",
    imageAlt: "헤리티지 콘서트 야외 대형 무대와 LED 스크린 설치 전경",
    images: buildImages("heritage-concert", 8, "헤리티지 콘서트"),
  },
  {
    slug: "sungkyul-univ-festival",
    title: "성결대 축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.05.26",
    region: "안양시",
    organizer: "성결대학교",
    folder: "(260526)성결대축제",
    image: "/images/portfolio/sungkyul-univ-festival.jpg",
    imageAlt: "성결대 축제 스캐폴드 무대와 LED 스크린 설치 전경",
    images: buildImages("sungkyul-univ-festival", 6, "성결대 축제"),
  },
  {
    slug: "osan-rose-festival",
    title: "오산 장미빛 축제",
    category: "지역축제",
    place: "야외",
    date: "2026.05.22",
    region: "오산시",
    organizer: "오산시",
    folder: "(260522)오산장미빛축제",
    image: "/images/portfolio/osan-rose-festival.jpg",
    imageAlt: "오산 장미빛 축제 야외 공연 무대와 LED 스크린 설치 전경",
    images: buildImages("osan-rose-festival", 2, "오산 장미빛 축제"),
  },
  {
    slug: "champions-live-concert",
    title: "챔피온스 축하공연",
    category: "콘서트",
    place: "야외",
    date: "2026.05.19",
    region: "수원시",
    organizer: "수원시",
    folder: "(260519)챔피온스축하공연",
    image: "/images/portfolio/champions-live-concert.jpg",
    imageAlt: "수원FC 챔피온스 축하공연 야외 무대 설치 전경",
    images: buildImages("champions-live-concert", 6, "챔피온스 축하공연"),
  },
  {
    slug: "duksung-womens-univ-festival-stage",
    title: "덕성여대 축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.05.12",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260512)덕성여대축제",
    image: "/images/portfolio/duksung-womens-univ-festival-stage.jpg",
    imageAlt: "덕성여대 축제 야간 무대와 트러스 조명 설치 전경",
    images: buildImages("duksung-womens-univ-festival-stage", 4, "덕성여대 축제"),
  },
  {
    slug: "duksung-womens-univ-festival-photozone",
    title: "덕성여대 축제 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.05.12",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260512)덕성여대포토존",
    image: "/images/portfolio/duksung-womens-univ-festival-photozone.jpg",
    imageAlt: "덕성여대 축제 포토존 배너 설치 전경",
    images: buildImages("duksung-womens-univ-festival-photozone", 3, "덕성여대 축제 포토존"),
  },
  {
    slug: "busan-open-tennis",
    title: "부산오픈 테니스",
    category: "스포츠",
    place: "야외",
    date: "2026.04.09",
    region: "부산시",
    organizer: "부산시 / RENAULT",
    folder: "(260409)부산오픈테니스",
    image: "/images/portfolio/busan-open-tennis.jpg",
    imageAlt: "부산오픈 테니스대회 경기장 브랜드 사인물 설치 전경",
    images: buildImages("busan-open-tennis", 4, "부산오픈 테니스"),
  },
  {
    slug: "skku-club-festival-stage",
    title: "성균관대 동아리축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.03.24",
    region: "서울시",
    organizer: "성균관대",
    folder: "(260324)성균관대동아리축제",
    image: "/images/portfolio/skku-club-festival-stage.jpg",
    imageAlt: "성균관대 동아리축제 야외 무대와 LED 스크린 설치 전경",
    images: buildImages("skku-club-festival-stage", 3, "성균관대 동아리축제"),
  },
  {
    slug: "skku-club-festival-photozone",
    title: "성균관대 동아리축제 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.03.24",
    region: "서울시",
    organizer: "성균관대",
    folder: "(260324)성균관대동아리축제 포토존",
    image: "/images/portfolio/skku-club-festival-photozone.jpg",
    imageAlt: "성균관대 동아리축제 일러스트 포토존 백드롭 설치 전경",
    images: buildImages("skku-club-festival-photozone", 3, "성균관대 동아리축제 포토존"),
  },
  {
    slug: "seoul-open-3-cushion-billiards",
    title: "서울오픈 3쿠션 당구대회",
    category: "스포츠",
    place: "실내",
    date: "2026.03.23",
    region: "서울시",
    organizer: "수협은행",
    folder: "(260323)서울오픈3쿠션당구대회",
    image: "/images/portfolio/seoul-open-3-cushion-billiards.jpg",
    imageAlt: "서울오픈 3쿠션 당구대회 브랜드 백드롭과 경기 테이블 설치 전경",
    images: buildImages("seoul-open-3-cushion-billiards", 6, "서울오픈 3쿠션 당구대회"),
  },
  {
    slug: "indoor-badminton-center-opening-ceremony",
    title: "실내배드민턴장 개관식",
    category: "기념식",
    place: "실내",
    date: "2026.03.18",
    region: "수원시",
    organizer: "수원시",
    folder: "(260318)실내배드민턴장 개관식",
    image: "/images/portfolio/indoor-badminton-center-opening-ceremony.jpg",
    imageAlt: "실내배드민턴장 개관식 무대 설치 전경",
    images: buildImages("indoor-badminton-center-opening-ceremony", 3, "실내배드민턴장 개관식"),
  },
];

export const portfolioItems: PortfolioItem[] = rawPortfolioItems.map((item) => ({
  ...item,
  imageBlurDataURL: portfolioBlurMap[item.image],
}));

export function getPortfolioBySlug(slug: string) {
  return portfolioItems.find((item) => item.slug === slug);
}
