import type { PortfolioItem } from "@/lib/types";
import { withBasePath } from "@/lib/base-path";
import { portfolioBlurMap } from "@/lib/content/portfolio-blur";

function buildImages(slug: string, count: number, title: string) {
  return Array.from({ length: count }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    const rawSrc = `/images/portfolio/${slug}/${n}.jpg`;
    return {
      src: withBasePath(rawSrc),
      alt: `${title} 현장 사진 ${i + 1}`,
      blurDataURL: portfolioBlurMap[rawSrc],
    };
  });
}

type RawPortfolioItem = Omit<PortfolioItem, "cardImage" | "imageBlurDataURL" | "cardImageBlurDataURL">;

// "사진자료 내용정리.xlsx" 폴더명 기준으로 img_org/recent/ 실제 시공 사진과 매칭한 데이터입니다.
const rawPortfolioItems: RawPortfolioItem[] = [
  {
    slug: "un-forces-memorial-ceremony",
    title: "유엔군초전기념 추도식",
    category: "기념식",
    place: "야외",
    date: "2026.06.30",
    region: "오산시",
    organizer: "오산시",
    folder: "(260630)유엔군 초전기념 추도식",
    image: "/images/portfolio/un-forces-memorial-ceremony.jpg",
    imageAlt: "유엔군초전기념 추도식 야외 무대와 각국 국기 설치 전경",
    images: buildImages("un-forces-memorial-ceremony", 8, "유엔군초전기념 추도식"),
  },
  {
    slug: "memorial-theme-park",
    title: "메모리얼 테마파크",
    category: "팝업행사",
    place: "야외",
    date: "2026.06.26",
    region: "수원시",
    organizer: "경기남부보훈지청",
    folder: "(260626)메모리얼 테마파크",
    image: "/images/portfolio/memorial-theme-park.jpg",
    imageAlt: "메모리얼 테마파크 야외 게이트 조형물과 부스 설치 전경",
    images: buildImages("memorial-theme-park", 15, "메모리얼 테마파크"),
  },
  {
    slug: "heritage-concert",
    title: "헤리티지 콘서트",
    category: "콘서트",
    place: "야외",
    date: "2026.06.13",
    region: "수원시",
    organizer: "수원시 / OBS",
    folder: "(260613)헤리티지 콘서트",
    image: "/images/portfolio/heritage-concert.jpg",
    imageAlt: "헤리티지 콘서트 야외 대형 무대와 LED 스크린 설치 전경",
    images: buildImages("heritage-concert", 8, "헤리티지 콘서트"),
  },
  {
    slug: "sungkyul-univ-festival",
    title: "성결대 축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.05.26",
    region: "안양시",
    organizer: "성결대학교",
    folder: "(260526)성결대축제",
    image: "/images/portfolio/sungkyul-univ-festival.jpg",
    imageAlt: "성결대 축제 스캐폴드 무대와 LED 스크린 설치 전경",
    images: buildImages("sungkyul-univ-festival", 6, "성결대 축제"),
  },
  {
    slug: "osan-rose-festival",
    title: "오산 장미빛 축제",
    category: "지역축제",
    place: "야외",
    date: "2026.05.22",
    region: "오산시",
    organizer: "오산시",
    folder: "(260522)오산장미빛축제",
    image: "/images/portfolio/osan-rose-festival.jpg",
    imageAlt: "오산 장미빛 축제 야외 공연 무대와 LED 스크린 설치 전경",
    images: buildImages("osan-rose-festival", 2, "오산 장미빛 축제"),
  },
  {
    slug: "champions-live-concert",
    title: "챔피온스 축하공연",
    category: "콘서트",
    place: "야외",
    date: "2026.05.19",
    region: "수원시",
    organizer: "수원시",
    folder: "(260519)챔피온스축하공연",
    image: "/images/portfolio/champions-live-concert.jpg",
    imageAlt: "수원FC 챔피온스 축하공연 야외 무대 설치 전경",
    images: buildImages("champions-live-concert", 6, "챔피온스 축하공연"),
  },
  {
    slug: "duksung-womens-univ-festival-stage",
    title: "덕성여대 축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.05.12",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260512)덕성여대축제",
    image: "/images/portfolio/duksung-womens-univ-festival-stage.jpg",
    imageAlt: "덕성여대 축제 야간 무대와 트러스 조명 설치 전경",
    images: buildImages("duksung-womens-univ-festival-stage", 4, "덕성여대 축제"),
  },
  {
    slug: "duksung-womens-univ-festival-photozone",
    title: "덕성여대 축제 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.05.12",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260512)덕성여대포토존",
    image: "/images/portfolio/duksung-womens-univ-festival-photozone.jpg",
    imageAlt: "덕성여대 축제 포토존 배너 설치 전경",
    images: buildImages("duksung-womens-univ-festival-photozone", 3, "덕성여대 축제 포토존"),
  },
  {
    slug: "busan-open-tennis",
    title: "부산오픈 테니스",
    category: "스포츠",
    place: "야외",
    date: "2026.04.09",
    region: "부산시",
    organizer: "부산시 / RENAULT",
    folder: "(260409)부산오픈테니스",
    image: "/images/portfolio/busan-open-tennis.jpg",
    imageAlt: "부산오픈 테니스대회 경기장 브랜드 사인물 설치 전경",
    images: buildImages("busan-open-tennis", 4, "부산오픈 테니스"),
  },
  {
    slug: "skku-club-festival-stage",
    title: "성균관대 동아리축제",
    category: "대학교축제",
    place: "야외",
    date: "2026.03.24",
    region: "서울시",
    organizer: "성균관대",
    folder: "(260324)성균관대동아리축제",
    image: "/images/portfolio/skku-club-festival-stage.jpg",
    imageAlt: "성균관대 동아리축제 야외 무대와 LED 스크린 설치 전경",
    images: buildImages("skku-club-festival-stage", 3, "성균관대 동아리축제"),
  },
  {
    slug: "skku-club-festival-photozone",
    title: "성균관대 동아리축제 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.03.24",
    region: "서울시",
    organizer: "성균관대",
    folder: "(260324)성균관대동아리축제 포토존",
    image: "/images/portfolio/skku-club-festival-photozone.jpg",
    imageAlt: "성균관대 동아리축제 일러스트 포토존 백드롭 설치 전경",
    images: buildImages("skku-club-festival-photozone", 3, "성균관대 동아리축제 포토존"),
  },
  {
    slug: "seoul-open-3-cushion-billiards",
    title: "서울오픈 3쿠션 당구대회",
    category: "스포츠",
    place: "실내",
    date: "2026.03.23",
    region: "서울시",
    organizer: "수협은행",
    folder: "(260323)서울오픈3쿠션당구대회",
    image: "/images/portfolio/seoul-open-3-cushion-billiards.jpg",
    imageAlt: "서울오픈 3쿠션 당구대회 브랜드 백드롭과 경기 테이블 설치 전경",
    images: buildImages("seoul-open-3-cushion-billiards", 6, "서울오픈 3쿠션 당구대회"),
  },
  {
    slug: "indoor-badminton-center-opening-ceremony",
    title: "실내배드민턴장 개관식",
    category: "기념식",
    place: "실내",
    date: "2026.03.18",
    region: "수원시",
    organizer: "수원시",
    folder: "(260318)실내배드민턴장 개관식",
    image: "/images/portfolio/indoor-badminton-center-opening-ceremony.jpg",
    imageAlt: "실내배드민턴장 개관식 무대 설치 전경",
    images: buildImages("indoor-badminton-center-opening-ceremony", 3, "실내배드민턴장 개관식"),
  },
  {
    slug: "duksung-univ-entrance-ceremony",
    title: "덕성여대 입학식",
    category: "기념식",
    place: "실내",
    date: "2026.02.26",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260226)덕성여대입학식",
    image: "/images/portfolio/duksung-univ-entrance-ceremony.jpg",
    imageAlt: "덕성여대 입학식 실내 무대와 음향 설치 전경",
    images: buildImages("duksung-univ-entrance-ceremony", 4, "덕성여대 입학식"),
  },
  {
    slug: "duksung-univ-entrance-ceremony-photozone",
    title: "덕성여대 입학식 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.02.26",
    region: "서울시",
    organizer: "덕성여대",
    folder: "(260226)덕성여대입학식 포토존",
    image: "/images/portfolio/duksung-univ-entrance-ceremony-photozone.jpg",
    imageAlt: "덕성여대 입학식 포토존 백드롭 설치 전경",
    images: buildImages("duksung-univ-entrance-ceremony-photozone", 4, "덕성여대 입학식 포토존"),
  },
  {
    slug: "sogang-univ-commencement-stage",
    title: "서강대 학위수여식",
    category: "기념식",
    place: "실내",
    date: "2026.02.19",
    region: "서울시",
    organizer: "서강대",
    folder: "(260219)서강대학위수여식",
    image: "/images/portfolio/sogang-univ-commencement-stage.jpg",
    imageAlt: "서강대 학위수여식 실내 무대와 조명 설치 전경",
    images: buildImages("sogang-univ-commencement-stage", 6, "서강대 학위수여식"),
  },
  {
    slug: "sogang-univ-commencement-photozone",
    title: "서강대 학위수여식 포토존",
    category: "포토존",
    place: "야외",
    date: "2026.02.19",
    region: "서울시",
    organizer: "서강대",
    folder: "(260219)서강대학위수여식 포토존",
    image: "/images/portfolio/sogang-univ-commencement-photozone.jpg",
    imageAlt: "서강대 학위수여식 포토존 백드롭 설치 전경",
    images: buildImages("sogang-univ-commencement-photozone", 4, "서강대 학위수여식 포토존"),
  },
  {
    slug: "davis-cup-tennis",
    title: "데이비스컵 테니스대회",
    category: "스포츠",
    place: "실내",
    date: "2026.02.01",
    region: "부산시",
    organizer: "부산시 / 하나증권",
    folder: "(260201)데이비스컵테니스대회",
    image: "/images/portfolio/davis-cup-tennis.jpg",
    imageAlt: "데이비스컵 테니스대회 실내 경기장 코트 설치 전경",
    images: buildImages("davis-cup-tennis", 8, "데이비스컵 테니스대회"),
  },
  {
    slug: "geumgok-dong-library-groundbreaking",
    title: "금곡동 도서관 기공식",
    category: "기공식",
    place: "야외",
    date: "2026.01.27",
    region: "수원시",
    organizer: "수원시",
    folder: "(260127)금곡동도서관기공식",
    image: "/images/portfolio/geumgok-dong-library-groundbreaking.jpg",
    imageAlt: "금곡동 도서관 건립사업 기공식 야외 무대 설치 전경",
    images: buildImages("geumgok-dong-library-groundbreaking", 4, "금곡동 도서관 기공식"),
  },
  {
    slug: "2025-songguyeongsin-concert",
    title: "2025 송구영신음악회",
    category: "콘서트",
    place: "야외",
    date: "2025.12.30",
    region: "수원시",
    organizer: "수원시",
    folder: "(251230)2025송구영신음악회",
    image: "/images/portfolio/2025-songguyeongsin-concert.jpg",
    imageAlt: "2025 송구영신음악회 화성행궁 광장 야외 무대 설치 전경",
    images: buildImages("2025-songguyeongsin-concert", 3, "2025 송구영신음악회"),
  },
  {
    slug: "suwon-arts-center-swing-door",
    title: "경기아트센터 스윙도어 제작",
    category: "공사/제작",
    place: "실내",
    date: "2025.12.29",
    region: "수원시",
    organizer: "수원시",
    folder: "(251229)스윙도어제작",
    image: "/images/portfolio/suwon-arts-center-swing-door.jpg",
    imageAlt: "경기아트센터 객석 스윙도어 제작·설치 전경",
    images: buildImages("suwon-arts-center-swing-door", 4, "경기아트센터 스윙도어 제작"),
  },
  {
    slug: "uri-financial-group-abl-merger-ceremony",
    title: "우리금융그룹 ABL 합병식",
    category: "기념식",
    place: "실내",
    date: "2025.12.17",
    region: "용인시",
    organizer: "우리금융그룹",
    folder: "(251217)우리금융그룹 ABL 합병식",
    image: "/images/portfolio/uri-financial-group-abl-merger-ceremony.jpg",
    imageAlt: "우리금융그룹 ABL 합병식 실내 무대 브랜드 백드롭 설치 전경",
    images: buildImages("uri-financial-group-abl-merger-ceremony", 3, "우리금융그룹 ABL 합병식"),
  },
  {
    slug: "suwon-cultural-foundation-partition-wall",
    title: "수원문화재단 가벽공사",
    category: "공사/제작",
    place: "실내",
    date: "2025.12.03",
    region: "수원시",
    organizer: "수원문화재단",
    folder: "(251203)수원문화재단가벽공사",
    image: "/images/portfolio/suwon-cultural-foundation-partition-wall.jpg",
    imageAlt: "수원문화재단 로비 가벽 및 미디어월 제작·설치 전경",
    images: buildImages("suwon-cultural-foundation-partition-wall", 7, "수원문화재단 가벽공사"),
  },
  {
    slug: "sports-science-international-seminar",
    title: "스포츠과학 국제세미나",
    category: "스포츠",
    place: "실내",
    date: "2025.11.24",
    region: "용인시",
    organizer: "용인시",
    folder: "(251124)스포츠과학국제세미나",
    image: "/images/portfolio/sports-science-international-seminar.jpg",
    imageAlt: "스포츠과학 국제세미나 실내 강당 LED 스크린 설치 전경",
    images: buildImages("sports-science-international-seminar", 4, "스포츠과학 국제세미나"),
  },
  {
    slug: "hamhyeon-high-school-festival",
    title: "함현고 축제",
    category: "고교축제",
    place: "실내",
    date: "2025.11.20",
    region: "시흥시",
    organizer: "함현고",
    folder: "(251120)함현고축제",
    image: "/images/portfolio/hamhyeon-high-school-festival.jpg",
    imageAlt: "함현고 동아리 발표회 및 함줄제 실내 무대 설치 전경",
    images: buildImages("hamhyeon-high-school-festival", 3, "함현고 축제"),
  },
  {
    slug: "suwon-youth-international-art-exchange",
    title: "수원초중학생 국제교류작품전",
    category: "기념식",
    place: "실내",
    date: "2025.11.18",
    region: "수원시",
    organizer: "수원시립만석전시관",
    folder: "(251118)수원초중학생국제교류작품전",
    image: "/images/portfolio/suwon-youth-international-art-exchange.jpg",
    imageAlt: "수원초중학생 국제교류작품전 전시장 무대 배경 설치 전경",
    images: buildImages("suwon-youth-international-art-exchange", 3, "수원초중학생 국제교류작품전"),
  },
  {
    slug: "manwithamission-concert",
    title: "맨위드어미션 콘서트",
    category: "콘서트",
    place: "실내",
    date: "2025.11.17",
    region: "서울시",
    organizer: "YES24 LIVE HALL",
    folder: "(251117)맨위드어미션콘서트",
    image: "/images/portfolio/manwithamission-concert.jpg",
    imageAlt: "맨위드어미션 콘서트 실내 공연장 무대 설치 전경",
    images: buildImages("manwithamission-concert", 4, "맨위드어미션 콘서트"),
  },
  {
    slug: "hanyang-cyber-univ-big-festival",
    title: "한양사이버대 빅페스티벌",
    category: "대학교축제",
    place: "실내",
    date: "2025.11.14",
    region: "서울시",
    organizer: "한양사이버대학교",
    folder: "(251114)한양대빅버드페스티벌",
    image: "/images/portfolio/hanyang-cyber-univ-big-festival.jpg",
    imageAlt: "한양사이버대 빅페스티벌 실내 체육관 무대 설치 전경",
    images: buildImages("hanyang-cyber-univ-big-festival", 5, "한양사이버대 빅페스티벌"),
  },
  {
    slug: "hanyang-cyber-univ-big-festival-photozone",
    title: "한양사이버대 빅페스티벌 포토존",
    category: "포토존",
    place: "야외",
    date: "2025.11.14",
    region: "서울시",
    organizer: "한양사이버대학교",
    folder: "(251114)한양대빅버드페스티벌 포토존",
    image: "/images/portfolio/hanyang-cyber-univ-big-festival-photozone.jpg",
    imageAlt: "한양사이버대 빅페스티벌 포토존 배너 설치 전경",
    images: buildImages("hanyang-cyber-univ-big-festival-photozone", 3, "한양사이버대 빅페스티벌 포토존"),
  },
  {
    slug: "seorang-reservoir-groundbreaking",
    title: "서랑저수지 시민힐링공간 조성사업 착공식",
    category: "기공식",
    place: "야외",
    date: "2025.11.10",
    region: "오산시",
    organizer: "오산시 / 대명건설",
    folder: "(251110)서랑저수지시민힐링공간 착공식",
    image: "/images/portfolio/seorang-reservoir-groundbreaking.jpg",
    imageAlt: "서랑저수지 시민힐링공간 조성사업 착공식 야외 무대 설치 전경",
    images: buildImages("seorang-reservoir-groundbreaking", 4, "서랑저수지 시민힐링공간 조성사업 착공식"),
  },
  {
    slug: "gyeonggi-foreign-talent-conference",
    title: "경기도 외국인 우수인재 컨퍼런스",
    category: "기념식",
    place: "실내",
    date: "2025.11.03",
    region: "수원시",
    organizer: "경기도",
    folder: "(251103)경기도외국인우수인재컨퍼런스",
    image: "/images/portfolio/gyeonggi-foreign-talent-conference.jpg",
    imageAlt: "경기도 외국인 우수인재 유치 컨퍼런스 실내 무대 설치 전경",
    images: buildImages("gyeonggi-foreign-talent-conference", 3, "경기도 외국인 우수인재 컨퍼런스"),
  },
];

export const portfolioItems: PortfolioItem[] = rawPortfolioItems.map((item) => {
  const cardImage = `/images/portfolio/${item.slug}-card.jpg`;
  return {
    ...item,
    imageBlurDataURL: portfolioBlurMap[item.image],
    cardImage,
    cardImageBlurDataURL: portfolioBlurMap[cardImage],
  };
});

export function getPortfolioBySlug(slug: string) {
  return portfolioItems.find((item) => item.slug === slug);
}
